### ISSUE TITLE
Login Doesn't Work

### ISSUE THREAD

**Issue by evan153** [sunnyguan/diepio-clone#1]
How to play it?

**Comment by sunnyguan** [comment]
Have you installed MongoDB and all the other dependencies?

**Comment by sunnyguan** [comment]
If you did, write a random username and a random password in to the corresponding boxes and click sign up. Then click sign in.

**Comment by sunnyguan** [comment]
@evan153 Also, you need to start the MongoDB server first.

**Comment by evan153** [comment]
Oh, I didn't get MongoDB :sob:

**Comment by sunnyguan** [comment]
Then get it :)

**Comment by sunnyguan** [comment]
Just download it from the official site and follow the instructions.

**Comment by evan153** [comment]
Will do boss.
So what experience do you have in programming? I found the same tutorial you linked here and your comment. I wanted to make a diep clone as well :laughing:

**Comment by sunnyguan** [comment]
Do you want to continue this in email instead? This is an issue page :)
My email is sunny.peng.guan@gmail.com.

**Comment by evan153** [comment]
Haha, sorry. Can we use gitter instead?

**Comment by sunnyguan** [comment]
Sure!

**Comment by sunnyguan** [comment]
Updated readme to included better instructions.
